// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientAction.proto

package message.core;

public final class ClientActionProto {
  private ClientActionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * <pre>
   *客户端请求命令列表
   * </pre>
   *
   * Protobuf enum {@code message.core.ClientAction}
   */
  public enum ClientAction
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <pre>
     *心跳;PB.player.HeartBeatReq;PB.player.HeartBeatRsp
     * </pre>
     *
     * <code>ACTION_HEARTBEAT = 1;</code>
     */
    ACTION_HEARTBEAT(1),
    ;

    /**
     * <pre>
     *心跳;PB.player.HeartBeatReq;PB.player.HeartBeatRsp
     * </pre>
     *
     * <code>ACTION_HEARTBEAT = 1;</code>
     */
    public static final int ACTION_HEARTBEAT_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ClientAction valueOf(int value) {
      return forNumber(value);
    }

    public static ClientAction forNumber(int value) {
      switch (value) {
        case 1: return ACTION_HEARTBEAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ClientAction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ClientAction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ClientAction>() {
            public ClientAction findValueByNumber(int number) {
              return ClientAction.forNumber(number);
            }
          };

    private final int value;

    private ClientAction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:message.core.ClientAction)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
