// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/ClientAction.proto

package message.core;

public final class ClientActionProto {
  private ClientActionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * <pre>
   *客户端请求命令列表
   * </pre>
   *
   * Protobuf enum {@code message.core.ClientAction}
   */
  public enum ClientAction
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <pre>
     *心跳;
     * </pre>
     *
     * <code>ACTION_HEARTBEAT = 1;</code>
     */
    ACTION_HEARTBEAT(1),
    /**
     * <pre>
     *登录;
     * </pre>
     *
     * <code>ACTION_LOGIN = 2;</code>
     */
    ACTION_LOGIN(2),
    /**
     * <pre>
     *创建房间;
     * </pre>
     *
     * <code>ACTION_CREAT_ROOM = 3;</code>
     */
    ACTION_CREAT_ROOM(3),
    /**
     * <pre>
     *进入房间;
     * </pre>
     *
     * <code>ACTION_JOIN_ROOM = 4;</code>
     */
    ACTION_JOIN_ROOM(4),
    /**
     * <pre>
     *离开房间
     * </pre>
     *
     * <code>ACTION_QUIT_ROOM = 5;</code>
     */
    ACTION_QUIT_ROOM(5),
    /**
     * <pre>
     *发送文本消息
     * </pre>
     *
     * <code>ACTION_SEND_TXT_MSG = 6;</code>
     */
    ACTION_SEND_TXT_MSG(6),
    ;

    /**
     * <pre>
     *心跳;
     * </pre>
     *
     * <code>ACTION_HEARTBEAT = 1;</code>
     */
    public static final int ACTION_HEARTBEAT_VALUE = 1;
    /**
     * <pre>
     *登录;
     * </pre>
     *
     * <code>ACTION_LOGIN = 2;</code>
     */
    public static final int ACTION_LOGIN_VALUE = 2;
    /**
     * <pre>
     *创建房间;
     * </pre>
     *
     * <code>ACTION_CREAT_ROOM = 3;</code>
     */
    public static final int ACTION_CREAT_ROOM_VALUE = 3;
    /**
     * <pre>
     *进入房间;
     * </pre>
     *
     * <code>ACTION_JOIN_ROOM = 4;</code>
     */
    public static final int ACTION_JOIN_ROOM_VALUE = 4;
    /**
     * <pre>
     *离开房间
     * </pre>
     *
     * <code>ACTION_QUIT_ROOM = 5;</code>
     */
    public static final int ACTION_QUIT_ROOM_VALUE = 5;
    /**
     * <pre>
     *发送文本消息
     * </pre>
     *
     * <code>ACTION_SEND_TXT_MSG = 6;</code>
     */
    public static final int ACTION_SEND_TXT_MSG_VALUE = 6;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ClientAction valueOf(int value) {
      return forNumber(value);
    }

    public static ClientAction forNumber(int value) {
      switch (value) {
        case 1: return ACTION_HEARTBEAT;
        case 2: return ACTION_LOGIN;
        case 3: return ACTION_CREAT_ROOM;
        case 4: return ACTION_JOIN_ROOM;
        case 5: return ACTION_QUIT_ROOM;
        case 6: return ACTION_SEND_TXT_MSG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ClientAction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ClientAction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ClientAction>() {
            public ClientAction findValueByNumber(int number) {
              return ClientAction.forNumber(number);
            }
          };

    private final int value;

    private ClientAction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:message.core.ClientAction)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
