// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushMsg.proto

package message.core;

public final class PushMsgProto {
  private PushMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * <pre>
   * 推送数据类型
   * </pre>
   *
   * Protobuf enum {@code message.core.PushType}
   */
  public enum PushType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <pre>
     *玩家数据
     * </pre>
     *
     * <code>PUSH_PLAYER = 1;</code>
     */
    PUSH_PLAYER(1),
    ;

    /**
     * <pre>
     *玩家数据
     * </pre>
     *
     * <code>PUSH_PLAYER = 1;</code>
     */
    public static final int PUSH_PLAYER_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PushType valueOf(int value) {
      return forNumber(value);
    }

    public static PushType forNumber(int value) {
      switch (value) {
        case 1: return PUSH_PLAYER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PushType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PushType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PushType>() {
            public PushType findValueByNumber(int number) {
              return PushType.forNumber(number);
            }
          };

    private final int value;

    private PushType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:message.core.PushType)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
